name: CI
#on: [push]
on: [pull_request]

jobs:
  tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #Passos
      #Intalação de biblioteca
      #Rodar compose install
      #Rodar testes automatizados
      #Etc

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master        
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}